### ISSUE TITLE
检测zygisk在smaps中找不到libandroid_runtime.so

### ISSUE THREAD

**Issue by Jecobo** [5ec1cff/my-notes#4]
大佬，在尝试您提供的zygisk检测方案中，我尝试去读去/proc/self/smaps中的内容，发现没有libandroid_runtime.so这个so相关的信息，代码如下：
    FILE *statusFile = fopen("/proc/self/smaps", "r");
    char *line = nullptr;
    size_t len = 0;
    while (getline(&line, &len, statusFile) != -1) {
        LOGI("line data: %s", line);
    }
    free(line);
但是我用objection枚举出所有的模块，是有libandroid_runtime.so这个文件的，我不知道是不是我读取内存的位置不对，希望大佬解答

**Comment by 5ec1cff** [comment]
什么叫没有，你改写上面的程序复制一份 /proc/self/smaps 出来看看有没有

**Comment by Jecobo** [comment]
非常感谢您的回答，复制下来确实是有libandroid_runtime.so，而且我找到了四条记录
7d1fa4d000-7d1faea000 r--p 00000000 fc:05 3210                           /system/lib64/libandroid_runtime.so
Size:                628 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 448 kB
Pss:                   5 kB
Shared_Clean:        448 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:          388 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd mr mw me 
7d1faea000-7d1fbdd000 r-xp 0009d000 fc:05 3210                           /system/lib64/libandroid_runtime.so
Size:                972 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                 752 kB
Pss:                  40 kB
Shared_Clean:        752 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:          652 kB
Anonymous:             0 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd ex mr mw me 
7d1fbdd000-7d1fbf6000 r--p 00190000 fc:05 3210                           /system/lib64/libandroid_runtime.so
Size:                100 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                  68 kB
Pss:                   0 kB
Shared_Clean:          0 kB
Shared_Dirty:         68 kB
Private_Clean:         0 kB
Private_Dirty:         0 kB
Referenced:           60 kB
Anonymous:            68 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                 32 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd mr mw me ac 
7d1fbf6000-7d1fbf8000 rw-p 001a8000 fc:05 3210                           /system/lib64/libandroid_runtime.so
Size:                  8 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   8 kB
Pss:                   8 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         8 kB
Referenced:            8 kB
Anonymous:             8 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr mr mw me ac 

但是r--p权限所对应的page的Private_Dirty没有值，这种情况是不是就算没有检测到Zygisk？（我把测试的app加入了magisk的排查列表）

**Comment by 5ec1cff** [comment]
@TimerZz007 这种检测方法早就修了

**Comment by Jecobo** [comment]
好的，谢谢大佬，对于新的Zygisk检测有什么方向吗？

**Comment by 5ec1cff** [comment]
自己探索
